name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: demo-spring-boot-0210
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_TAG: ${{ github.sha }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AKS_RESOURCE_GROUP: aks-demo-alb-rg
  AKS_CLUSTER_NAME: demo
  AKS_NAMESPACE: demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn package -DskipTests

    # login in registry
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
            username: ${{ env.DOCKER_USERNAME }}
            password: ${{ env.DOCKER_PASSWORD }}
            registry: ${{ env.DOCKER_REGISTRY }}

    # build container image
      - name: Build dockerfile 
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG}} .

    # push container image
      - name: Push dockerfile 
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG}}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
    
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

      - name: Replace IMAGE_TAG in application.yaml
        run: sed -i "s/\$IMAGE_TAG/${{ env.DOCKER_TAG }}/g" k8s/application.yaml

      - name: Deploy to AKS
        run: kubectl apply -f k8s/application.yaml -n ${{ env.AKS_NAMESPACE }}
